### ISSUE TITLE
 sudo: unable to resolve host aio: Name or service not known

### ISSUE THREAD

**Issue by Jagadeeshftw** [electrocucaracha/openstack-multinode#163]
JagadeeshB@Jagadeesh MINGW64 ~/Downloads
$ cd openstack-multinode-master

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master
$ ls
openstack-multinode-master/

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master
$ cd openstack-multinode-master/

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master
$ ls
LICENSE    bindep.txt              commons.sh*     defaults.env*          etc/            mlc_config.json  releases.txt     samples/  tox.ini
Makefile   ci/                     compute.sh*     distros_supported.yml  insecure_keys/  node.sh*         requirements/    scripts/  undercloud.sh*
README.md  codebase-structure.svg  controller.sh*  doc/                   install.sh*     registry.sh*     run_kaction.sh*  spec/     upgrade.sh*

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master
$ ls
LICENSE    bindep.txt              commons.sh*     defaults.env*          etc/            mlc_config.json  releases.txt     samples/  tox.ini
Makefile   ci/                     compute.sh*     distros_supported.yml  insecure_keys/  node.sh*         requirements/    scripts/  undercloud.sh*
README.md  codebase-structure.svg  controller.sh*  doc/                   install.sh*     registry.sh*     run_kaction.sh*  spec/     upgrade.sh*

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master
$ cd samples/

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master/samples
$ ls
README.md  aio/  distributed/  noha/

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master/samples
$ cd aio

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master/samples/aio
$ ls
README.md  Vagrantfile  hosts.ini

JagadeeshB@Jagadeesh MINGW64 ~/Downloads/openstack-multinode-master/openstack-multinode-master/samples/aio
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'debian/bullseye64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 11.20230615.1
==> default: Loading metadata for box 'debian/bullseye64'
    default: URL: https://vagrantcloud.com/debian/bullseye64
==> default: Adding box 'debian/bullseye64' (v11.20230615.1) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/debian/boxes/bullseye64/versions/11.20230615.1/providers/virtualbox/unknown/vagrant.box
    default:
==> default: Successfully added box 'debian/bullseye64' (v11.20230615.1) for 'virtualbox'!
==> default: Importing base box 'debian/bullseye64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: aio_default_1703309159635_18431
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 6080 (guest) => 6080 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 6.0.0 r127566
    default: VirtualBox Version: 7.0
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/JagadeeshB/Downloads/openstack-multinode-master/openstack-multinode-master
==> default: Running provisioner: shell...
    default: Running: C:/Users/JAGADE~1/AppData/Local/Temp/vagrant-shell20231223-24320-y9hkee.sh
    default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    default: Selecting previously unselected package libcurl4:amd64.
    default: (Reading database ... 25146 files and directories currently installed.)
    default: Preparing to unpack .../libcurl4_7.74.0-1.3+deb11u10_amd64.deb ...
    default: Unpacking libcurl4:amd64 (7.74.0-1.3+deb11u10) ...
    default: Selecting previously unselected package curl.
    default: Preparing to unpack .../curl_7.74.0-1.3+deb11u10_amd64.deb ...
    default: Unpacking curl (7.74.0-1.3+deb11u10) ...
    default: Setting up libcurl4:amd64 (7.74.0-1.3+deb11u10) ...
    default: Setting up curl (7.74.0-1.3+deb11u10) ...
    default: Processing triggers for man-db (2.9.4-2) ...
    default: Processing triggers for libc-bin (2.31-13+deb11u6) ...
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Generating public/private rsa key pair.
    default: Enter file in which to save the key (/home/vagrant/.ssh/id_rsa): Your identification has been saved in /home/vagrant/.ssh/id_rsa
    default: Your public key has been saved in /home/vagrant/.ssh/id_rsa.pub
    default: The key fingerprint is:
    default: SHA256:oUt2IWymWok97FqnmktLKQqs2ASxYiIn4eygrxjM8Ig vagrant@aio
    default: The key's randomart image is:
    default: +---[RSA 3072]----+
    default: |                 |
    default: |     .           |
    default: |o     = o        |
    default: |o+ + = o o       |
    default: |X+o B + S        |
    default: |#* = + o         |
    default: |E=B o o          |
    default: |*O = o           |
    default: |*.Oo.            |
    default: +----[SHA256]-----+
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjwp0yEf3s5PnXEHVZ/Hq6sDK30z28PC5U+IiyLTjYYFSRErFyLIAe0+q8THIRNj8X76Nj0DlWnIMqXNm7iOgah2ZA+RcHtW9FnipRDla2iPyYRpLvfboemdo8pJmtiR13YscUfjX1xe73K9bKRLn6GXBG3wlurSA/KtPohbMspPFhymVnDoQGdFJ9Zn9iWrvFxkKI81K0Yl1hJPowWqQOm+e/teT7BmDXvXKY70jxA/DEs/NnE7Scgbqx+RUPPj9VtxaOfRBtjCGQXpA1raNDMBlTFEHo9+fKCQMb18k1OzqhCaIJja143AzfGQbCC5fkECYa51mVAz0riiyzk6OI6WpBMlCmVVyi+wgxC8NEPDzg303yG+9+n1fs+zgcr8cfvu5fs5TSU507HLTLBFmeeYIZCVquv8mxTcRLTWLr3IW8vBlNFUK4Y3f6giXeydYULXBem9nlRMNjWYYm6kAIktO2g1PX66Sbne2w0HYSqY4d0fivKN+S156Cqiv1swU= vagrant@aio
==> default: Running provisioner: shell...
    default: Running: inline script
    default: ++ sudo ip link add veth0 type veth peer name veth1
    default: ++ source /etc/os-release
    default: +++ PRETTY_NAME='Debian GNU/Linux 11 (bullseye)'
    default: +++ NAME='Debian GNU/Linux'
    default: +++ VERSION_ID=11
    default: +++ VERSION='11 (bullseye)'
    default: +++ VERSION_CODENAME=bullseye
    default: +++ ID=debian
    default: +++ HOME_URL=https://www.debian.org/
    default: +++ SUPPORT_URL=https://www.debian.org/support
    default: +++ BUG_REPORT_URL=https://bugs.debian.org/
    default: ++ case ${ID,,} in
    default: ++ sudo ip link set dev veth0 up
    default: ++ command -v brctl
    default: ++ sudo apt-get update
    default: Hit:1 https://deb.debian.org/debian bullseye InRelease
    default: Hit:2 https://security.debian.org/debian-security bullseye-security InRelease
    default: Hit:3 https://deb.debian.org/debian bullseye-updates InRelease
    default: Hit:4 https://deb.debian.org/debian bullseye-backports InRelease
    default: Reading package lists...
    default: ++ sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --reinstall --no-install-recommends bridge-utils
    default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    default: Selecting previously unselected package bridge-utils.
    default: (Reading database ... 25161 files and directories currently installed.)
    default: Preparing to unpack .../bridge-utils_1.7-1_amd64.deb ...
    default: Unpacking bridge-utils (1.7-1) ...
    default: Setting up bridge-utils (1.7-1) ...
    default: Processing triggers for man-db (2.9.4-2) ...
    default: ++ sudo brctl addbr uplinkbridge
    default: ++ sudo brctl addif uplinkbridge veth0
    default: ++ sudo ip link set uplinkbridge up
    default: ++ sudo ip addr add 10.10.13.7/24 dev veth0
    default: ++ sudo ip route show
    default: default via 10.0.2.2 dev eth0
    default: 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
    default: 10.10.13.0/24 dev veth0 proto kernel scope link src 10.10.13.7 linkdown
    default: ++ sudo mkdir -p /etc/rc.d/
    default: ++ sudo tee /etc/rc.d/rc.local
    default: #!/bin/bash
    default: sudo ip link add veth0 type veth peer name veth1
    default: sudo ip addr add 10.10.13.7/24 dev veth0
    default: ++ sudo chmod +x /etc/rc.d/rc.local
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
    default: 127.0.0.1 localhost
    default: sudo: unable to resolve host aio: Name or service not known
    default: sfdisk: cannot open /dev/sdb: No such file or directory
    default: Node setup process: 0 secs
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_KOLLA_INSTALL_TYPE=binary
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_MAGNUM=no
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_HORIZON=
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_KOLLA_INTERNAL_VIP_ADDRESS=10.0.2.15
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_FOLDER=/vagrant/
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_KOLLA_BASE_DISTRO=debian
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_NEUTRON_PROVIDER_NETWORKS=yes
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_NEUTRON_EXTERNAL_INTERFACE=veth0
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_RUN_INIT=
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_NETWORK_INTERFACE=eth0
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_HEAT=no
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_DEPLOY_PROFILE=minimal
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: dpkg-query: no packages found matching python-cryptography
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default:
    default: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    default:
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: Package 'python3-openssl' is not installed, so not removed
    default: Package 'python3-cryptography' is not installed, so not removed
    default: The following packages were automatically installed and are no longer required:
    default:   libcurl3-gnutls python3-certifi python3-chardet python3-dbus
    default:   python3-debianbts python3-httplib2 python3-idna python3-pkg-resources
    default:   python3-pycurl python3-pysimplesoap python3-requests python3-six
    default:   python3-urllib3
    default: Use 'sudo apt autoremove' to remove them.
    default: The following packages will be REMOVED:
    default:   python3-debian python3-distro-info python3-reportbug reportbug
    default:   unattended-upgrades
    default: 0 upgraded, 0 newly installed, 5 to remove and 52 not upgraded.
    default: After this operation, 1388 kB disk space will be freed.
(Reading database ... 25191 files and directories currently installed.)
    default: Removing reportbug (7.10.3+deb11u1) ...
    default: Removing python3-reportbug (7.10.3+deb11u1) ...
    default: Removing python3-debian (0.1.39) ...
    default: Removing unattended-upgrades (2.8) ...
    default: Removing python3-distro-info (1.0) ...
    default: Processing triggers for man-db (2.9.4-2) ...
    default: curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443
    default: Provisioning process: 16 secs
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by electrocucaracha** [comment]
Hi @Jagadeeshftw, thanks for reporting this issue. I'll try to replicate this in my local environment, at quick glance it seems like your Windows host is not resolving the domain name of your Debian guest (`sudo: unable to resolve host aio: Name or service not known`). I suspect that this occurs when it tries to install some dependencies, like [here](https://github.com/electrocucaracha/openstack-multinode/blob/master/node.sh#L67). If that is the case, I suggest replacing all the references [in the same way that I do it in the CI](https://github.com/electrocucaracha/openstack-multinode/blob/master/.github/actions/vagrant-setup/action.yml#L36-L41). Let me know if that replacement solves the issue.

**Comment by Jagadeeshftw** [comment]
@electrocucaracha Which references i need to replace?

**Comment by electrocucaracha** [comment]
[These are the MacOS instructions](https://github.com/electrocucaracha/openstack-multinode/blob/master/.github/actions/vagrant-setup/action.yml#L36-L41), but technically you have to replace the shorten links:
* `http://bit.ly/install_pkg` with `https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/install.sh`
* `http://bit.ly/install_bin` with `https://raw.githubusercontent.com/electrocucaracha/pkg-mgr_scripts/master/bindep_install.sh`

Be careful with MS editors like notepad, sometimes they add some end line characters that affect bash scripts.

**Comment by Jagadeeshftw** [comment]
╰─λ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/bullseye64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: aio_default_1703350797884_69418
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 6080 (guest) => 6080 (host) (adapter 1)
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 6.0.0 r127566
    default: VirtualBox Version: 7.0
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/JagadeeshB/Downloads/openstack-multinode-master/openstack-multinode-master
==> default: Running provisioner: shell...
    default: Running: C:/Users/JAGADE~1/AppData/Local/Temp/vagrant-shell20231223-864-q8vwo.sh
    default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    default: Selecting previously unselected package libcurl4:amd64.
    default: (Reading database ... 25146 files and directories currently installed.)
    default: Preparing to unpack .../libcurl4_7.74.0-1.3+deb11u10_amd64.deb ...
    default: Unpacking libcurl4:amd64 (7.74.0-1.3+deb11u10) ...
    default: Selecting previously unselected package curl.
    default: Preparing to unpack .../curl_7.74.0-1.3+deb11u10_amd64.deb ...
    default: Unpacking curl (7.74.0-1.3+deb11u10) ...
    default: Setting up libcurl4:amd64 (7.74.0-1.3+deb11u10) ...
    default: Setting up curl (7.74.0-1.3+deb11u10) ...
    default: Processing triggers for man-db (2.9.4-2) ...
    default: Processing triggers for libc-bin (2.31-13+deb11u6) ...
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Generating public/private rsa key pair.
    default: Enter file in which to save the key (/home/vagrant/.ssh/id_rsa): Your identification has been saved in /home/vagrant/.ssh/id_rsa
    default: Your public key has been saved in /home/vagrant/.ssh/id_rsa.pub
    default: The key fingerprint is:
    default: SHA256:V7uedjeC2ZgNZXV8SgAyxey2zBhNgcDVVa2i5Xapxdk vagrant@aio
    default: The key's randomart image is:
    default: +---[RSA 3072]----+
    default: |     ..o+*++oo.o |
    default: |      . .o=   ..=|
    default: |         +  ...oo|
    default: |        . +.o+o  |
    default: |        S*.=+o + |
    default: |        ..=.o.* E|
    default: |           .X+   |
    default: |           *o=...|
    default: |           .o....|
    default: +----[SHA256]-----+
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDxBw612dd0FG9EAWNFCddMZld2Lvg2yZXv780VLjzJxKkJM2jh0gJC2Pyq/KAIGtZRNTF+PlaBJNittyw6Jfe3S3qH6FNn6VAe+pudpO0gyfz/mee2/iHNDwbFAdGM8bzCK6/lV5FB9NKnT/ZDsCxSAANEMxHYrW0gU1/F7SpF+JFioazz8qe2fM+URhae2lWkEUTZIs1mBibj4mzvcUAZDZx4hGWwDoCiOHgtSDpkSsOTjvy2W6RiyFQbq+Vi/7DGtxM1I8Ed9wluPWJuK9E5GIqKB9rMVAEo8Wk0PjoByrKxHpLOcKdKkV2h5oLnwNjVx1azLqgdq2o4xPoqJc2U5bOhvLGbT2yJi3a59PHY72opyhblNZVbX2p3QysdZDev4b+ldMgnngFvdCaqZ31NJCtSzHyClHAy+x77dH8Hfk4tFQzRF0qh73PJHxE7rorx5jwyJPD1Y7Jjopedm8EIoRxpxmHG4ENLqpNbe7GNXvl16Uw5DYb63kyKSzuud80= vagrant@aio
==> default: Running provisioner: shell...
    default: Running: inline script
    default: ++ sudo ip link add veth0 type veth peer name veth1
    default: ++ source /etc/os-release
    default: +++ PRETTY_NAME='Debian GNU/Linux 11 (bullseye)'
    default: +++ NAME='Debian GNU/Linux'
    default: +++ VERSION_ID=11
    default: +++ VERSION='11 (bullseye)'
    default: +++ VERSION_CODENAME=bullseye
    default: +++ ID=debian
    default: +++ HOME_URL=https://www.debian.org/
    default: +++ SUPPORT_URL=https://www.debian.org/support
    default: +++ BUG_REPORT_URL=https://bugs.debian.org/
    default: ++ case ${ID,,} in
    default: ++ sudo ip link set dev veth0 up
    default: ++ command -v brctl
    default: ++ sudo apt-get update
    default: Hit:1 https://deb.debian.org/debian bullseye InRelease
    default: Hit:2 https://deb.debian.org/debian bullseye-updates InRelease
    default: Hit:3 https://security.debian.org/debian-security bullseye-security InRelease
    default: Hit:4 https://deb.debian.org/debian bullseye-backports InRelease
    default: Reading package lists...
    default: ++ sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --reinstall --no-install-recommends bridge-utils
    default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    default: Selecting previously unselected package bridge-utils.
    default: (Reading database ... 25161 files and directories currently installed.)
    default: Preparing to unpack .../bridge-utils_1.7-1_amd64.deb ...
    default: Unpacking bridge-utils (1.7-1) ...
    default: Setting up bridge-utils (1.7-1) ...
    default: Processing triggers for man-db (2.9.4-2) ...
    default: ++ sudo brctl addbr uplinkbridge
    default: ++ sudo brctl addif uplinkbridge veth0
    default: ++ sudo ip link set uplinkbridge up
    default: ++ sudo ip addr add 10.10.13.7/24 dev veth0
    default: ++ sudo ip route show
    default: default via 10.0.2.2 dev eth0
    default: 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15
    default: 10.10.13.0/24 dev veth0 proto kernel scope link src 10.10.13.7 linkdown
    default: ++ sudo mkdir -p /etc/rc.d/
    default: ++ sudo tee /etc/rc.d/rc.local
    default: #!/bin/bash
    default: sudo ip link add veth0 type veth peer name veth1
    default: sudo ip addr add 10.10.13.7/24 dev veth0
    default: ++ sudo chmod +x /etc/rc.d/rc.local
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
    default: 127.0.0.1 localhost
    default: sudo: unable to resolve host aio: Name or service not known
    default: sfdisk: cannot open /dev/sdb: No such file or directory
    default: Node setup process: 2 secs
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_KOLLA_INSTALL_TYPE=binary
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_MAGNUM=no
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_HORIZON=
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_KOLLA_INTERNAL_VIP_ADDRESS=10.0.2.15
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_FOLDER=/vagrant/
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_KOLLA_BASE_DISTRO=debian
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_NEUTRON_PROVIDER_NETWORKS=yes
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_NEUTRON_EXTERNAL_INTERFACE=veth0
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_RUN_INIT=
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_NETWORK_INTERFACE=eth0
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_ENABLE_HEAT=no
    default: sudo: unable to resolve host aio: Name or service not known
    default: export OS_KOLLA_DEPLOY_PROFILE=minimal
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: dpkg-query: no packages found matching python-cryptography
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default: sudo: unable to resolve host aio: Name or service not known
    default:
    default: WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    default:
    default: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: Package 'python3-openssl' is not installed, so not removed
    default: Package 'python3-cryptography' is not installed, so not removed
    default: The following packages were automatically installed and are no longer required:
    default:   libcurl3-gnutls python3-certifi python3-chardet python3-dbus
    default:   python3-debianbts python3-httplib2 python3-idna python3-pkg-resources
    default:   python3-pycurl python3-pysimplesoap python3-requests python3-six
    default:   python3-urllib3
    default: Use 'sudo apt autoremove' to remove them.
    default: The following packages will be REMOVED:
    default:   python3-debian python3-distro-info python3-reportbug reportbug
    default:   unattended-upgrades
    default: 0 upgraded, 0 newly installed, 5 to remove and 52 not upgraded.
    default: After this operation, 1388 kB disk space will be freed.
(Reading database ... 25191 files and directories currently installed.)
    default: Removing reportbug (7.10.3+deb11u1) ...
    default: Removing python3-reportbug (7.10.3+deb11u1) ...
    default: Removing python3-debian (0.1.39) ...
    default: Removing unattended-upgrades (2.8) ...
    default: Removing python3-distro-info (1.0) ...
    default: Processing triggers for man-db (2.9.4-2) ...
    default: curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to raw.githubusercontent.com:443
    default: Provisioning process: 6 secs
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.


Still facing same issue even after replacing the links

**Comment by electrocucaracha** [comment]
Are you host located behind a proxy? Maybe you need to add an entry into the Vagrantfile to use the same host resolver. What about adding [this solution](https://superuser.com/a/722670) as part of the [VirtualBox instructions](https://github.com/electrocucaracha/openstack-multinode/blob/master/samples/aio/Vagrantfile#L154-L164)

**Comment by Jagadeeshftw** [comment]
> Are you host located behind a proxy? Maybe you need to add an entry into the Vagrantfile to use the same host resolver. What about adding [this solution](https://superuser.com/a/722670) as part of the [VirtualBox instructions](https://github.com/electrocucaracha/openstack-multinode/blob/master/samples/aio/Vagrantfile#L154-L164)

Yes, i think, I'm using company laptop. 

<img width="671" alt="image" src="https://github.com/electrocucaracha/openstack-multinode/assets/92681651/fc4ca132-bd17-4007-8780-16df334037b1">
I have modified the vagrantfile but still facing same issues

**Comment by electrocucaracha** [comment]
@Jagadeeshftw I'm going to close this issue, given that it's affected by your network setup. Feel free to add more information to help others to troubleshoot it.
