### ISSUE TITLE
 compute01: An error occurred. The error will be shown after all tasks complete.

### ISSUE THREAD

**Issue by rmros** [electrocucaracha/openstack-multinode#2]
i have some errors:
i run vagrant up command in root / ubuntu 18.04

==> network02: Waiting for domain to get an IP address...
==> control03: Creating shared folders metadata...
==> compute01: Creating shared folders metadata...
==> control03: Starting domain.
==> compute01: Starting domain.
**==> compute01: An error occurred. The error will be shown after all tasks complete.**
==> control03: Waiting for domain to get an IP address...
==> control01: Waiting for SSH to become available...
==> control01: Setting hostname...
==> registry: Waiting for SSH to become available...
==> control02: Waiting for SSH to become available...

==> control03: Configuring and enabling network interfaces...
==> storage01: Rsyncing folder: /root/openstack-multinode/ => /vagrant
    **control01: dpkg-preconfigure: unable to re-open stdin: No such file or directory**
==> control02: Rsyncing folder: /root/openstack-multinode/ => /vagrant
    control01: Fetched 17.5 kB in 2s (5,993 B/s)
==> network02: Rsyncing folder: /root/openstack-multinode/ => /vagrant
==> monitoring01: Rsyncing folder: /root/openstack-multinode/ => /vagrant
==> registry: Rsyncing folder: /root/openstack-multinode/ => /vagrant

and 

    registry: 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
    registry: + curl -sL https://bootstrap.pypa.io/get-pip.py
    registry: + sudo python
    registry: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    registry: WARNING: The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    registry: WARNING: The directory '/home/vagrant/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    registry: Collecting pip
    registry:   Downloading https://files.pythonhosted.org/packages/8d/07/f7d7ced2f97ca3098c16565efbe6b15fafcba53e8d9bdb431e09140514b0/pip-19.2.2-py2.py3-none-any.whl (1.4MB)
    registry: ERROR: Exception:
    registry: Traceback (most recent call last):
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/cli/base_command.py", line 188, in main
    registry:     status = self.run(options, args)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/commands/install.py", line 345, in run
    registry:     resolver.resolve(requirement_set)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/legacy_resolve.py", line 196, in resolve
    registry:     self._resolve_one(requirement_set, req)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    registry:     abstract_dist = self._get_abstract_dist_for(req_to_install)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    registry:     self.require_hashes
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    registry:     progress_bar=self.progress_bar
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/download.py", line 1064, in unpack_url
    registry:     progress_bar=progress_bar
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/download.py", line 924, in unpack_http_url
    registry:     progress_bar)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/download.py", line 1152, in _download_http_url
    registry:     _download_url(resp, link, content_file, hashes, progress_bar)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/download.py", line 861, in _download_url
    registry:     hashes.check_against_chunks(downloaded_chunks)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/utils/hashes.py", line 75, in check_against_chunks
    registry:     for chunk in chunks:
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/download.py", line 829, in written_chunks
    registry:     for chunk in chunks:
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/utils/ui.py", line 156, in iter
    registry:     for x in it:
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_internal/download.py", line 818, in resp_read
    registry:     decode_content=False):
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_vendor/urllib3/response.py", line 531, in stream
    registry:     data = self.read(amt=amt, decode_content=decode_content)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_vendor/urllib3/response.py", line 496, in read
    registry:     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
    registry:   File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    registry:     self.gen.throw(type, value, traceback)
    registry:   File "/tmp/tmpyugW2D/pip.zip/pip/_vendor/urllib3/response.py", line 411, in _error_catcher
    registry:     raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    registry: ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
==> registry: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'registry'
machine. Please handle this error then try again:

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

An error occurred while executing the action on the 'compute01'
machine. Please handle this error then try again:

There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: internal error: process exited while connecting to monitor: 2019-08-21T11:50:58.232597Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory

**Comment by electrocucaracha** [comment]
Thanks @rmros for reporting this issue. I used a Ubuntu Xenial server for developing and testing this project so I'll have to figure out how can I reproduce these errors. But in the meantime, can you validate few things:
* Verify internet access from the Registry VM, it seem like you had a timeout during the provisioning process.
```
    $ vagrant ssh registry
    $ curl -sL https://bootstrap.pypa.io/get-pip.py | python
```
* Get Libvirt and QEMU versions. Apparently the version that you have doesn't support [Vagrant memory instruction](https://github.com/electrocucaracha/openstack-multinode/blob/master/Vagrantfile#L82)
```
    $ qemu-system-x86_64 --version
    QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.15~cloud1)
    Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
    $ virsh --version
    4.0.0
```
BTW did you install *Vagrant* and their dependencies thru the [setup.sh](https://github.com/electrocucaracha/openstack-multinode/blob/master/setup.sh) script, I haven't tested in an Ubuntu Bionic server so more likely it'll need some changes.

**Comment by rmros** [comment]
@electrocucaracha im thanks you created this project

do i need run these instructions root level or use sudo or nopasswd user?

i will try install raw ubuntu  xenial desktop 
and then ./setup.sh -p libvirt and vagrant up
i will report to you

**Comment by electrocucaracha** [comment]
You don't need to run those instructions with `sudo` because the *setup.sh* already has them. I recommend to have sudo password-less account to avoid any prompt during the execution.

You don't need `sudo` for *vagrant* neither as long as your account has loaded the [Libvirt's permissions](https://github.com/electrocucaracha/openstack-multinode/blob/master/setup.sh#L199)
