### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by rmros** [electrocucaracha/openstack-multinode#3]
i tested:
vagrant up  in not root
and also vagrant up

ramin@server:~/openstack-multinode$ sudo vagrant up
[INFO] Linux Distro: ubuntu 
Bringing machine 'registry' up with 'libvirt' provider...
Bringing machine 'control01' up with 'libvirt' provider...
Bringing machine 'control02' up with 'libvirt' provider...
Bringing machine 'control03' up with 'libvirt' provider...
Bringing machine 'compute01' up with 'libvirt' provider...
Bringing machine 'network01' up with 'libvirt' provider...
Bringing machine 'network02' up with 'libvirt' provider...
Bringing machine 'network03' up with 'libvirt' provider...
Bringing machine 'storage01' up with 'libvirt' provider...
Bringing machine 'monitoring01' up with 'libvirt' provider...
==> control02: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> network03: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> network02: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> registry: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> monitoring01: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> compute01: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> network01: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> control01: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> control03: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> storage01: Checking if box 'elastic/ubuntu-16.04-x86_64' version '20180210.0.0' is up to date...
==> network03: Creating image (snapshot of base box volume).
==> registry: Creating image (snapshot of base box volume).
==> network03: Creating domain with the following settings...
==> network03:  -- Name:              openstack-multinode_network03_1566390589_028a5590a7733a8e5f70
==> network03:  -- Domain type:       kvm
==> network02: Creating image (snapshot of base box volume).
==> network03:  -- Cpus:              4
==> registry: Creating domain with the following settings...
==> network03:  -- Feature:           acpi
==> network02: Creating domain with the following settings...
==> registry:  -- Name:              openstack-multinode_registry_1566390589_afc4cee1d47500f330db
==> network02:  -- Name:              openstack-multinode_network02_1566390590_6755b47f13d027105781
==> registry:  -- Domain type:       kvm
==> network02:  -- Domain type:       kvm
==> network02:  -- Cpus:              4
==> network03:  -- Feature:           apic
==> registry:  -- Cpus:              4
==> network02:  -- Feature:           acpi
==> network03:  -- Feature:           pae
==> registry:  -- Feature:           acpi
==> network02:  -- Feature:           apic
==> registry:  -- Feature:           apic
==> registry:  -- Feature:           pae
==> network03:  -- Memory:            8192M
==> network02:  -- Feature:           pae
==> registry:  -- Memory:            16384M
==> network03:  -- Management MAC:    
==> network02:  -- Memory:            8192M
==> registry:  -- Management MAC:    
==> registry:  -- Loader:            
==> network02:  -- Management MAC:    
==> registry:  -- Nvram:             
==> network03:  -- Loader:            
==> network03:  -- Nvram:             
==> network02:  -- Loader:            
==> registry:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> network03:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> registry:  -- Storage pool:      default
==> network03:  -- Storage pool:      default
==> registry:  -- Image:             /var/lib/libvirt/images/openstack-multinode_registry_1566390589_afc4cee1d47500f330db.img (20G)
==> network03:  -- Image:             /var/lib/libvirt/images/openstack-multinode_network03_1566390589_028a5590a7733a8e5f70.img (20G)
==> network02:  -- Nvram:             
==> registry:  -- Volume Cache:      default
==> network03:  -- Volume Cache:      default
==> network03:  -- Kernel:            
==> registry:  -- Kernel:            
==> network02:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> network03:  -- Initrd:            
==> network02:  -- Storage pool:      default
==> registry:  -- Initrd:            
==> network03:  -- Graphics Type:     vnc
==> network02:  -- Image:             /var/lib/libvirt/images/openstack-multinode_network02_1566390590_6755b47f13d027105781.img (20G)
==> registry:  -- Graphics Type:     vnc
==> network03:  -- Graphics Port:     -1
==> network02:  -- Volume Cache:      default
==> network02:  -- Kernel:            
==> registry:  -- Graphics Port:     -1
==> network03:  -- Graphics IP:       127.0.0.1
==> network02:  -- Initrd:            
==> network02:  -- Graphics Type:     vnc
==> network02:  -- Graphics Port:     -1
==> network03:  -- Graphics Password: Not defined
==> registry:  -- Graphics IP:       127.0.0.1
==> network02:  -- Graphics IP:       127.0.0.1
==> network03:  -- Video Type:        cirrus
==> registry:  -- Graphics Password: Not defined
==> network02:  -- Graphics Password: Not defined
==> network03:  -- Video VRAM:        9216
==> registry:  -- Video Type:        cirrus
==> network02:  -- Video Type:        cirrus
==> network03:  -- Sound Type:	
==> registry:  -- Video VRAM:        9216
==> network03:  -- Keymap:            en-us
==> registry:  -- Sound Type:	
==> network02:  -- Video VRAM:        9216
==> network03:  -- TPM Path:          
==> registry:  -- Keymap:            en-us
==> network02:  -- Sound Type:	
==> network03:  -- INPUT:             type=mouse, bus=ps2
==> registry:  -- TPM Path:          
==> network02:  -- Keymap:            en-us
==> network02:  -- TPM Path:          
==> registry:  -- Disks:         vdb(qcow2,100)
==> network02:  -- INPUT:             type=mouse, bus=ps2
==> registry:  -- Disk(vdb):     /var/lib/libvirt/images/openstack-multinode_registry_1566390589_afc4cee1d47500f330db-vdb.qcow2
==> registry:  -- INPUT:             type=mouse, bus=ps2
==> control01: Creating image (snapshot of base box volume).
==> control01: Creating domain with the following settings...
==> control01:  -- Name:              openstack-multinode_control01_1566390591_25eebc1826e350cef4f6
==> control01:  -- Domain type:       kvm
==> control01:  -- Cpus:              8
==> control01:  -- Feature:           acpi
==> control01:  -- Feature:           apic
==> control01:  -- Feature:           pae
==> control01:  -- Memory:            16384M
==> control01:  -- Management MAC:    
==> control01:  -- Loader:            
==> control01:  -- Nvram:             
==> control01:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> control01:  -- Storage pool:      default
==> control01:  -- Image:             /var/lib/libvirt/images/openstack-multinode_control01_1566390591_25eebc1826e350cef4f6.img (20G)
==> control01:  -- Volume Cache:      default
==> control01:  -- Kernel:            
==> control01:  -- Initrd:            
==> control01:  -- Graphics Type:     vnc
==> control01:  -- Graphics Port:     -1
==> control01:  -- Graphics IP:       127.0.0.1
==> control01:  -- Graphics Password: Not defined
==> control01:  -- Video Type:        cirrus
==> control01:  -- Video VRAM:        9216
==> control01:  -- Sound Type:	
==> control01:  -- Keymap:            en-us
==> control01:  -- TPM Path:          
==> control01:  -- INPUT:             type=mouse, bus=ps2
==> network03: Creating shared folders metadata...
==> network03: An error occurred. The error will be shown after all tasks complete.
==> network02: Creating shared folders metadata...
==> network02: An error occurred. The error will be shown after all tasks complete.
==> registry: Creating shared folders metadata...
==> registry: An error occurred. The error will be shown after all tasks complete.
==> monitoring01: Creating image (snapshot of base box volume).
==> monitoring01: Creating domain with the following settings...
==> monitoring01:  -- Name:              openstack-multinode_monitoring01_1566390592_296d0162a2e62850dc72
==> monitoring01:  -- Domain type:       kvm
==> monitoring01:  -- Cpus:              4
==> monitoring01:  -- Feature:           acpi
==> monitoring01:  -- Feature:           apic
==> monitoring01:  -- Feature:           pae
==> monitoring01:  -- Memory:            8192M
==> monitoring01:  -- Management MAC:    
==> monitoring01:  -- Loader:            
==> monitoring01:  -- Nvram:             
==> monitoring01:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> monitoring01:  -- Storage pool:      default
==> monitoring01:  -- Image:             /var/lib/libvirt/images/openstack-multinode_monitoring01_1566390592_296d0162a2e62850dc72.img (20G)
==> monitoring01:  -- Volume Cache:      default
==> monitoring01:  -- Kernel:            
==> monitoring01:  -- Initrd:            
==> monitoring01:  -- Graphics Type:     vnc
==> monitoring01:  -- Graphics Port:     -1
==> monitoring01:  -- Graphics IP:       127.0.0.1
==> monitoring01:  -- Graphics Password: Not defined
==> monitoring01:  -- Video Type:        cirrus
==> monitoring01:  -- Video VRAM:        9216
==> monitoring01:  -- Sound Type:	
==> monitoring01:  -- Keymap:            en-us
==> monitoring01:  -- TPM Path:          
==> monitoring01:  -- INPUT:             type=mouse, bus=ps2
==> control03: Creating image (snapshot of base box volume).
==> control03: Creating domain with the following settings...
==> control03:  -- Name:              openstack-multinode_control03_1566390592_7225f2d0ffad04451ff1
==> control03:  -- Domain type:       kvm
==> control03:  -- Cpus:              8
==> control01: Creating shared folders metadata...
==> control03:  -- Feature:           acpi
==> control03:  -- Feature:           apic
==> control01: An error occurred. The error will be shown after all tasks complete.
==> control03:  -- Feature:           pae
==> control03:  -- Memory:            16384M
==> control03:  -- Management MAC:    
==> control03:  -- Loader:            
==> control03:  -- Nvram:             
==> compute01: Creating image (snapshot of base box volume).
==> control03:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> control03:  -- Storage pool:      default
==> control03:  -- Image:             /var/lib/libvirt/images/openstack-multinode_control03_1566390592_7225f2d0ffad04451ff1.img (20G)
==> compute01: Creating domain with the following settings...
==> network01: Creating image (snapshot of base box volume).
==> storage01: Creating image (snapshot of base box volume).
==> compute01:  -- Name:              openstack-multinode_compute01_1566390593_16c3a73b222687a40d29
==> control03:  -- Volume Cache:      default
==> network01: Creating domain with the following settings...
==> network01:  -- Name:              openstack-multinode_network01_1566390593_b0ba8fee45553c5d7a32
==> network01:  -- Domain type:       kvm
==> control03:  -- Kernel:            
==> network01:  -- Cpus:              4
==> network01:  -- Feature:           acpi
==> network01:  -- Feature:           apic
==> compute01:  -- Domain type:       kvm
==> control03:  -- Initrd:            
==> network01:  -- Feature:           pae
==> storage01: Creating domain with the following settings...
==> compute01:  -- Cpus:              16
==> storage01:  -- Name:              openstack-multinode_storage01_1566390593_c26e72f53e62a95c533e
==> network01:  -- Memory:            8192M
==> control03:  -- Graphics Type:     vnc
==> compute01:  -- Feature:           acpi
==> storage01:  -- Domain type:       kvm
==> network01:  -- Management MAC:    
==> control03:  -- Graphics Port:     -1
==> compute01:  -- Feature:           apic
==> compute01:  -- Feature:           pae
==> storage01:  -- Cpus:              4
==> compute01:  -- Memory:            65536M
==> network01:  -- Loader:            
==> storage01:  -- Feature:           acpi
==> control03:  -- Graphics IP:       127.0.0.1
==> network01:  -- Nvram:             
==> compute01:  -- Management MAC:    
==> control03:  -- Graphics Password: Not defined
==> storage01:  -- Feature:           apic
==> network01:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> storage01:  -- Feature:           pae
==> storage01:  -- Memory:            8192M
==> control03:  -- Video Type:        cirrus
==> storage01:  -- Management MAC:    
==> compute01:  -- Loader:            
==> control03:  -- Video VRAM:        9216
==> network01:  -- Storage pool:      default
==> storage01:  -- Loader:            
==> compute01:  -- Nvram:             
==> control03:  -- Sound Type:	
==> control03:  -- Keymap:            en-us
==> compute01:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> network01:  -- Image:             /var/lib/libvirt/images/openstack-multinode_network01_1566390593_b0ba8fee45553c5d7a32.img (20G)
==> control03:  -- TPM Path:          
==> compute01:  -- Storage pool:      default
==> control03:  -- INPUT:             type=mouse, bus=ps2
==> storage01:  -- Nvram:             
==> network01:  -- Volume Cache:      default
==> storage01:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> compute01:  -- Image:             /var/lib/libvirt/images/openstack-multinode_compute01_1566390593_16c3a73b222687a40d29.img (20G)
==> storage01:  -- Storage pool:      default
==> storage01:  -- Image:             /var/lib/libvirt/images/openstack-multinode_storage01_1566390593_c26e72f53e62a95c533e.img (20G)
==> storage01:  -- Volume Cache:      default
==> storage01:  -- Kernel:            
==> compute01:  -- Volume Cache:      default
==> network01:  -- Kernel:            
==> storage01:  -- Initrd:            
==> compute01:  -- Kernel:            
==> storage01:  -- Graphics Type:     vnc
==> network01:  -- Initrd:            
==> compute01:  -- Initrd:            
==> storage01:  -- Graphics Port:     -1
==> compute01:  -- Graphics Type:     vnc
==> storage01:  -- Graphics IP:       127.0.0.1
==> compute01:  -- Graphics Port:     -1
==> network01:  -- Graphics Type:     vnc
==> network01:  -- Graphics Port:     -1
==> storage01:  -- Graphics Password: Not defined
==> compute01:  -- Graphics IP:       127.0.0.1
==> network01:  -- Graphics IP:       127.0.0.1
==> compute01:  -- Graphics Password: Not defined
==> storage01:  -- Video Type:        cirrus
==> storage01:  -- Video VRAM:        9216
==> compute01:  -- Video Type:        cirrus
==> storage01:  -- Sound Type:	
==> storage01:  -- Keymap:            en-us
==> network01:  -- Graphics Password: Not defined
==> storage01:  -- TPM Path:          
==> network01:  -- Video Type:        cirrus
==> compute01:  -- Video VRAM:        9216
==> network01:  -- Video VRAM:        9216
==> storage01:  -- INPUT:             type=mouse, bus=ps2
==> network01:  -- Sound Type:	
==> compute01:  -- Sound Type:	
==> compute01:  -- Keymap:            en-us
==> network01:  -- Keymap:            en-us
==> compute01:  -- TPM Path:          
==> monitoring01: Creating shared folders metadata...
==> network01:  -- TPM Path:          
==> compute01:  -- INPUT:             type=mouse, bus=ps2
==> network01:  -- INPUT:             type=mouse, bus=ps2
==> monitoring01: An error occurred. The error will be shown after all tasks complete.
==> control03: Creating shared folders metadata...
==> control03: An error occurred. The error will be shown after all tasks complete.
==> control02: Creating image (snapshot of base box volume).
==> control02: Creating domain with the following settings...
==> control02:  -- Name:              openstack-multinode_control02_1566390595_23ce309a8eab4efbdd34
==> control02:  -- Domain type:       kvm
==> control02:  -- Cpus:              8
==> control02:  -- Feature:           acpi
==> storage01: Creating shared folders metadata...
==> network01: Creating shared folders metadata...
==> control02:  -- Feature:           apic
==> storage01: An error occurred. The error will be shown after all tasks complete.
==> compute01: Creating shared folders metadata...
==> network01: An error occurred. The error will be shown after all tasks complete.
==> control02:  -- Feature:           pae
==> control02:  -- Memory:            16384M
==> compute01: An error occurred. The error will be shown after all tasks complete.
==> control02:  -- Management MAC:    
==> control02:  -- Loader:            
==> control02:  -- Nvram:             
==> control02:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> control02:  -- Storage pool:      default
==> control02:  -- Image:             /var/lib/libvirt/images/openstack-multinode_control02_1566390595_23ce309a8eab4efbdd34.img (20G)
==> control02:  -- Volume Cache:      default
==> control02:  -- Kernel:            
==> control02:  -- Initrd:            
==> control02:  -- Graphics Type:     vnc
==> control02:  -- Graphics Port:     -1
==> control02:  -- Graphics IP:       127.0.0.1
==> control02:  -- Graphics Password: Not defined
==> control02:  -- Video Type:        cirrus
==> control02:  -- Video VRAM:        9216
==> control02:  -- Sound Type:	
==> control02:  -- Keymap:            en-us
==> control02:  -- TPM Path:          
==> control02:  -- INPUT:             type=mouse, bus=ps2
==> control02: Creating shared folders metadata...
==> control02: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'registry'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'control01'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'control02'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'control03'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'compute01'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'network01'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'network02'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'network03'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'storage01'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

An error occurred while executing the action on the 'monitoring01'
machine. Please handle this error then try again:

Address 192.168.124.0 does not match with network name mgmt-net.
Please fix your configuration and run vagrant again.

**Comment by electrocucaracha** [comment]
These errors are caused by the [declaration](https://github.com/electrocucaracha/openstack-multinode/blob/master/Vagrantfile#L57) of the Management Network in Vagrantfile. You can comment out the lines for managing the Management Network (`management_network_address` and `management_network_name`) and let Vagrant to dynamically assign those values.  Those networks will be displayed with this command:
```
$ virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 mgmt-net active     no            yes
```
