### ISSUE TITLE
==> compute01: An error occurred. The error will be shown after all tasks complete.

### ISSUE THREAD

**Issue by rmros** [electrocucaracha/openstack-multinode#4]
im trying with xenial 
like its working
all the vm are running
but there is an error 
==> compute01: An error occurred. The error will be shown after all tasks complete.

==> control03:  -- Video Type:        cirrus
==> storage01:  -- Feature:           pae
==> network02:  -- Graphics Port:     -1
==> network02:  -- Graphics IP:       127.0.0.1
==> storage01:  -- Memory:            8192M
==> network02:  -- Graphics Password: Not defined
==> control03:  -- Video VRAM:        9216
==> network02:  -- Video Type:        cirrus
==> registry:  -- Volume Cache:      default
==> registry:  -- Kernel:            
==> network02:  -- Video VRAM:        9216
==> network02:  -- Sound Type:	
==> control03:  -- Sound Type:	
==> storage01:  -- Management MAC:    
==> registry:  -- Initrd:            
==> network02:  -- Keymap:            en-us
==> registry:  -- Graphics Type:     vnc
==> network02:  -- TPM Path:          
==> control03:  -- Keymap:            en-us
==> storage01:  -- Loader:            
==> storage01:  -- Nvram:             
==> network02:  -- INPUT:             type=mouse, bus=ps2
==> registry:  -- Graphics Port:     -1
==> storage01:  -- Base box:          elastic/ubuntu-16.04-x86_64
==> registry:  -- Graphics IP:       127.0.0.1
==> control03:  -- TPM Path:          
==> control03:  -- INPUT:             type=mouse, bus=ps2
==> registry:  -- Graphics Password: Not defined
==> storage01:  -- Storage pool:      default
==> storage01:  -- Image:             /var/lib/libvirt/images/openstack-multinode_storage01_1566453039_979339c811aa56f8198e.img (20G)
==> registry:  -- Video Type:        cirrus
==> storage01:  -- Volume Cache:      default
==> storage01:  -- Kernel:            
==> monitoring01: Creating shared folders metadata...
==> registry:  -- Video VRAM:        9216
==> storage01:  -- Initrd:            
==> registry:  -- Sound Type:	
==> storage01:  -- Graphics Type:     vnc
==> monitoring01: Starting domain.
==> registry:  -- Keymap:            en-us
==> storage01:  -- Graphics Port:     -1
==> storage01:  -- Graphics IP:       127.0.0.1
==> registry:  -- TPM Path:          
==> monitoring01: Waiting for domain to get an IP address...
==> storage01:  -- Graphics Password: Not defined
==> registry:  -- Disks:         vdb(qcow2,100)
==> storage01:  -- Video Type:        cirrus
==> registry:  -- Disk(vdb):     /var/lib/libvirt/images/openstack-multinode_registry_1566453038_69932918183f30fa6966-vdb.qcow2
==> storage01:  -- Video VRAM:        9216
==> registry:  -- INPUT:             type=mouse, bus=ps2
==> storage01:  -- Sound Type:	
==> storage01:  -- Keymap:            en-us
==> storage01:  -- TPM Path:          
==> storage01:  -- INPUT:             type=mouse, bus=ps2
==> control01: Creating shared folders metadata...
==> control01: Starting domain.
==> network01: Creating shared folders metadata...
==> control01: Waiting for domain to get an IP address...
==> network01: Starting domain.
==> network01: Waiting for domain to get an IP address...
==> compute01: Creating shared folders metadata...
==> compute01: Starting domain.
==> compute01: An error occurred. The error will be shown after all tasks complete.
==> network03: Creating shared folders metadata...
==> network03: Starting domain.
==> control02: Creating shared folders metadata...
==> control02: Starting domain.
==> network03: Waiting for domain to get an IP address...
==> control02: Waiting for domain to get an IP address...
==> control03: Creating shared folders metadata...
==> network02: Creating shared folders metadata...
==> registry: Creating shared folders metadata...
==> storage01: Creating shared folders metadata...
==> control03: Starting domain.
==> registry: Starting domain.
==> storage01: Starting domain.
==> network02: Starting domain.
==> control03: Waiting for domain to get an IP address...
==> monitoring01: Waiting for SSH to become available...
==> registry: Waiting for domain to get an IP address...
==> network01: Waiting for SSH to become available...
==> control01: Waiting for SSH to become available...
==> network02: Waiting for domain to get an IP address...
==> storage01: Waiting for domain to get an IP address...
==> monitoring01: Setting hostname...
==> control01: Setting hostname...
==> network01: Setting hostname...
==> network03: Waiting for SSH to become available...
==> network03: Setting hostname...
==> control02: Waiting for SSH to become available...
==> registry: Waiting for SSH to become available...
==> control03: Waiting for SSH to become available...
==> network02: Waiting for SSH to become available...
==> storage01: Waiting for SSH to become available...
==> control02: Setting hostname...
==> control03: Setting hostname...
==> registry: Setting hostname...
==> network02: Setting hostname...
==> storage01: Setting hostname...
==> monitoring01: Configuring and enabling network interfaces...
==> control01: Configuring and enabling network interfaces...
==> network01: Configuring and enabling network interfaces...
==> monitoring01: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> control01: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> network01: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> network03: Configuring and enabling network interfaces...
==> control02: Configuring and enabling network interfaces...
==> registry: Configuring and enabling network interfaces...
==> control03: Configuring and enabling network interfaces...
==> storage01: Configuring and enabling network interfaces...
==> network02: Configuring and enabling network interfaces...
==> network03: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> control02: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> control03: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> registry: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant
==> storage01: Rsyncing folder: /home/ramin/openstack-multinode/ => /vagrant

**Comment by electrocucaracha** [comment]
@rmros it seems like the logs are incomplete or are they failing on rsync task?

**Comment by electrocucaracha** [comment]
@rmros I'll close this issue, I don't have HW to reproduce it so I'll need more details about it
