### ISSUE TITLE
Does this works on macOS?

### ISSUE THREAD

**Issue by uhlhosting** [electrocucaracha/openstack-multinode#5]

**Comment by electrocucaracha** [comment]
I haven't tried yet but technically it could works as long as you have enough resources. If you want to try to deploy a local dev environment I suggest to use [Devstack](https://github.com/openstack/devstack)

**Comment by electrocucaracha** [comment]
The [All-in-One configuration](https://github.com/electrocucaracha/openstack-multinode/tree/master/samples/aio) can be deployed on a macOS using VMs provided by Vagrant. There is a way to control the amount of HW resources thru env variables, you can take a look on the [Travis CI info](https://github.com/electrocucaracha/openstack-multinode/blob/master/.travis.yml#L52-L56)
